import { Recipe } from "@/types/recipe";
import { categories } from "@/types/category";

export const recipes: Recipe[] = [
  {
    id: "1",
    title: "Spaghetti Carbonara",
    description: "Classic Italian pasta with eggs, cheese, and pancetta",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400",
    category: categories[0],
    isFavorite: true,
    time: "20 min",
    ingredients: [
      "2 cups all-purpose flour",
      "3 large eggs",
      "1/2 cup grated Parmesan cheese",
      "200g pancetta or bacon",
      "2 cloves garlic",
      "1/2 cup heavy cream",
      "Salt and black pepper to taste",
      "Fresh parsley for garnish",
    ],
    instructions: [
      "Bring a large pot of salted water to boil and cook pasta according to package directions.",
      "Meanwhile, cook pancetta in a large skillet over medium heat until crispy, about 5 minutes.",
      "Add minced garlic and cook for 1 minute until fragrant.",
      "In a bowl, whisk together eggs, Parmesan cheese, and heavy cream.",
      "Drain pasta, reserving 1/2 cup of pasta water.",
      "Add hot pasta to the skillet with pancetta and toss to combine.",
      "Remove from heat and quickly stir in egg mixture, adding pasta water as needed.",
      "Season with salt and pepper, garnish with parsley, and serve immediately.",
    ],
  },
  {
    id: "2",
    title: "Chicken Tikka Masala",
    description: "Creamy Indian curry with tender chicken pieces",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400",
    category: categories[1],
    isFavorite: false,
    time: "45 min",
    ingredients: [
      "1 kg chicken breast",
      "1 cup yogurt",
      "1/2 cup tomato puree",
      "1/2 cup cream",
      "1/2 cup coconut milk",
      "1/2 cup cashew nuts",
      "1/2 cup almonds",
      "1/2 cup raisins",
    ],
    instructions: [
      "Marinate the chicken in yogurt for 1 hour.",
      "Cook the chicken in a pan with oil until it's cooked.",
      "Add the tomato puree, cream, coconut milk, cashew nuts, and almonds to the pan.",
      "Cook the sauce until it's thick.",
      "Add the raisins to the sauce.",
      "Serve the chicken with the sauce.",
    ],
  },
  {
    id: "3",
    title: "Beef Tacos",
    description: "Mexican street-style tacos with seasoned beef",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400",
    category: categories[2],
    isFavorite: false,
    time: "30 min",
    ingredients: [
      "1 kg beef",
      "1 cup corn tortillas",
      "1/2 cup salsa",
      "1/2 cup guacamole",
      "1/2 cup sour cream",
      "1/2 cup cheese",
    ],
    instructions: [
      "Cook the beef in a pan with oil until it's cooked.",
      "Add the tortillas to the pan and cook until they're crispy.",
      "Add the salsa, guacamole, and sour cream to the pan.",
      "Add the cheese to the pan.",
      "Serve the tacos with the beef.",
    ],
  },
];
